# Generated by Django 5.0.6 on 2024-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=64)),
                ('data_nascimento', models.DateField()),
                ('genero_aluno', models.CharField(max_length=10)),
                ('documento_aluno', models.CharField(max_length=64)),
                ('endereco_aluno', models.CharField(max_length=64)),
                ('telefone_aluno', models.CharField(max_length=64)),
            ],
        ),
    ]
