# Generated by Django 5.0.6 on 2024-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asdavi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='condicoes_familiar',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_enfermidade',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_medicamento',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='renda_familiar',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
